- name: elasticsearch systemd
  systemd:
    name: elasticsearch
    enabled: yes
    state: started

- name: logstash systemd
  systemd:
    name: logstash
    enabled: yes
    state: started

- name: restart elasticsearch
  systemd:
    name: elasticsearch.service
    state: restarted

- name: restart logstash
  systemd:
    name: logstash.service
    state: restarted
