---
- name: Install filebeat
  apt:
    name=filebeat
    state=latest
  notify:
    - filebeat systemd

- name: filebeat.yml
  copy: src=/etc/ansible/roles/filebeat/files/filebeat.yml dest=/etc/filebeat/filebeat.yml
  notify:
    - filebeat restarted
