---
- name: Add Elastic repo
  apt_repository:
    repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
    state: present

- name: Update cache
  apt:
   update_cache: yes


- name: Install Elastic
  apt:
    name=elasticsearch
    state=latest
  notify:
    - elasticsearch systemd

- name: elasticsearch
  copy: src=/etc/ansible/roles/EL/files/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch


