---
- name: Install Nginx
  apt:
    name=nginx
    state=latest
  notify:
    - nginx systemd

- name: nginx_conf
  lineinfile: dest=/etc/nginx/nginx.conf
              regexp='^access_log'
              insertafter='^access_log'
              line='error_log /var/log/nginx/error.log;'
              state=present

- name: index.html
  copy: src=/etc/ansible/roles/nginx/files/index.html dest=/var/www/html/index.html
  notify:
    - restart nginx
