---
- name: Add Elastic repo
  apt_repository:
    repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
    state: present

- name: Update cache
  apt:
   update_cache: yes

- name: Install Kibana
  apt:
    name=kibana
    state=latest
  notify:
    - kibana systemd

- name: kibana
  copy: src=/etc/ansible/roles/kibana/files/kibana.yml dest=/etc/kibana/kibana.yml
  notify:
    - restart kibana
